---
apiVersion: v1
kind: Namespace
metadata:
  name: orchestra

---
apiVersion: v1
kind: Service
metadata:
  name: orchestration
  namespace: orchestra
spec:
  selector:
    app: orchestration
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: github
    port: 81
    targetPort: 8081

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: orchestration
  namespace: orchestra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestration
  template:
    metadata:
      labels:
        app: orchestration
    spec:
      containers:
      - name: orchestration
        image: orchestration:0.1.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        env:
        - name: ORCHESTRA_KUBE_URI
          value: https://kubernetes.default
        - name: ORCHESTRA_ELASTICSEARCH_URI
          value: elasticsearch://elasticsearch:9200
        - name: ORCHESTRA_BASEPATH
          value: /api/v1/namespaces/orchestra/services/orchestration:http/proxy
        - name: ORCHESTRA_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ORCHESTRA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
